"""add user models

Revision ID: d69d3f6dd6ad
Revises: 222329729b66
Create Date: 2026-09-06 23:22:25.523780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69d3f6dd6ad'
down_revision: Union[str, Sequence[str], None] = '222329729b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)
        batch_op.create_unique_constraint('uq_projects_owner_id_name', ['owner_id', 'name'])
        batch_op.create_foreign_key("fk_projects_owner_id_users", 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key("fk_tasks_owner_id_users", 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint("fk_tasks_owner_id_users", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_owner_id'))
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint("fk_projects_owner_id_users", type_='foreignkey')
        batch_op.drop_constraint('uq_projects_owner_id_name', type_='unique')
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
